version: '3'

services:
  web:
    image: django-simple-dbbackup:latest
    volumes:
      - .:/code
      - ~/bak/django-simple-dbbackup/:/home/bak/
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  db:
    image: postgres:12.0-alpine
